---
sudo: false
dist: trusty

language: ruby
cache: bundler
bundler_args: --without system_tests

before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v

script:
  - bundle exec rake $CHECK
matrix:
  fast_finish: true
  include:
    # Check that the module performs for Puppet 4.9.x
    - rvm: 2.3.1
      env: PUPPET_VERSION="~> 4.9" CHECK=spec

    # Check for conflict markers, whitespace errors, and unwanted files
    - rvm: 2.4.2
      env: PUPPET_VERSION="~> 5.0"
      script:
        - git diff --check
        - bundle exec rake check:dot_underscore check:test_file check:git_ignore check:symlinks

    # Check for syntax and linting errors
    - rvm: 2.4.2
      env: PUPPET_VERSION="~> 5.0" CHECK='validate lint rubocop syntax:hiera'

    # Check that the module performs for Puppet 5.0.x
    - rvm: 2.4.2
      env: PUPPET_VERSION="~> 5.0" CHECK=spec

    # Generate the Puppet Strings documentation (YARD)
    - rvm: 2.4.2
      env: PUPPET_VERSION="~> 5.0" CHECK=strings:generate PUBLISH_PAGES=true

    # Build the deployment artifact
    - rvm: 2.4.2
      env: PUPPET_VERSION="~> 5.0" CHECK=build DEPLOY_TO_FORGE=yes

branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/

notifications:
  email: false

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: docs
    on:
      branch: master
      condition: $PUBLISH_PAGES = true
  - provider: puppetforge
    skip_cleanup: true
    user: wwkimball
    password:
      secure: "fes8KsRx6IEmmx1n00Q2gC9QgmCJwme11Xq9QXfZ+UsEpN4H6zLPCXtZqJIw6s+6\
        WiqLy2AML0Fj8Coymag+u0DCh0kJCbLs7kChwFRoG5gSTzSIB4Z4WpnUiLAwnMwQbGEUTia\
        yRdRBqrc7Rg+Moaa5QVy5CPfsZpBR9lHWvPkVMLpn3UiwSkL9LFRp9xqZFezaeLYTHxTnq6\
        PTKM6ZlSnep92xzkAdK98mXMM7JtktctpAPCk4UPzFBY9rJaKVdoVQr+j7h710jdcrlL06j\
        vMpQKK3z31PI9l50Wa9JGvdqouD+KNL/WaIxIZforBAroQ8PbP5wNAbKkYiws+KtrmdqvfE\
        L7WSYdRrUOvvUBSJ2n9MwJakwLNmbw6iX/WOnStJp2+fcCjQGAgEk+mN3yoeF71F1HuMb89\
        yqkvq9pYiG/SGAJbwaix94aEEBC06Do7hMeD8ua6RAYhmhlQXIUCoB+JvVJvGLvMtpxPQTq\
        DXnNfdMGulKPt8BufNbcHO3fimND+R1svwabPAqDx91F91k49zqrlo7I0oZcHlAyNtxS8qt\
        Bdbm2uldbotxfr+G9a3YjXkOySvxZr89tnoFppkQPvGJ6W6hj5OPxzKGBW0mIK0MH2UPX5i\
        uK8OlKo0m0JuUnPotBMsAyNc0dW6NBgzE0Ulp9mASxzjIBtVihI="
    on:
      tags: true
      all_branches: true
      condition: $DEPLOY_TO_FORGE = yes
